# 공장을 만들꺼다 모델 공장

### 아이디어는 다음과 같습니다.

# 순서
### 1.전처리 : base 파일은 아무칼럼도 제거하지 않은 파일 -> 우리는 이 파일에서 몇개씩 칼럼을 제거하며 모델의 성능을 파악할 것임
        사용법 : 
        prepro() 함수를 사용하세요
        prepro("파일경로", ["삭제할 칼럼", "삭제할 칼럼2"]) --> 삭제할 칼럼 여러개를 집어넣어도 된다. 단 존재해야함
        prepro("파일경로") --> 삭제할 칼럼을 적지 않으면 삭제하지 않고 원핫인코딩한 pd를 리턴해준다
        df = prepro("파일경로") --> 이런식으로 df에 저장가능함

### 2.데이터 나누기 : 
        사용법 : 
        get() 함수를 사용하세요
        get("파일경로") --> 판다스 파일을 보내주면 알아서 train데이터 test데이터 validation데이터 나눠준다. 
                        비율은 train test가 8대2로 나눠지고 다시 train을 train validation으로 8대 2 나눔
        X_trn, y_trn, X_tst, y_tst = get('파일경로')  --> 이런식으로 리턴이 총4개 항목이기에 변수 4개에 넣어준다.

### 3.모델 여러개 만들기
        사용법 : 
                앞에 설명 존재

# 커스텀모델 함수를 사용해보자

### 인공신경망 만드는 함수
- factiory_model( 트레이닝 데이터(X값=칼럼=피쳐=열) ,  타겟 데이터(맞춰야하는 데이터) , 하이퍼 파라미터 셋팅한 json파일의 이름)
- -> EX :  factory_model(X_trn, y_trn,'config.json')

          리턴값(아웃풋)은 인공신경망 모델을 리턴함 학습도 가능함
          model = factory_model(X_trn, y_trn,'config.json')
          model.fit(X_trn, y_trn)
### 인공신경망 모델 여러개 만드는 함수
- create_models( 트레이닝 데이터(X값=칼럼=피쳐=열) ,  타겟 데이터(맞춰야하는 데이터), 하이퍼 파라미터 셋팅한 json파일의 이름 'configW.json' 무조건 W가 뒤에 붙어있어야함 , 몇개의 config.json파일을 넣을 것인지 )
- -> EX :  create_models(X_trn, y_trn,'configW.json',2)

          리턴값(아웃풋)은 인공신경망 모델 여러개를 담은 리스트를 리턴함 인덱스로 꺼내서 사용 가능함
          models = create_models(X_trn, y_trn,'configW.json',2)
          model1 = models[0]
### 인공신경만 모델에 대한 교차검증 함수
- CV(모델(한개의 모델), 트레이닝 데이터(X값=칼럼=피쳐=열) ,  타겟 데이터(맞춰야하는 데이터), 5번 교차 검증을 할 것이고 기본값이기에 안적어도 됨)
- -> EX :  CV(m, feature, label, n_splits=5)

          리턴값(아웃풋)은 판다스 데이터프레임이다 교차검증 후 5번 평균의 결과값을 가지고 있음 다음과 같이 프레임 확인도 가능함
          d = CV(m, feature, label, n_splits=5)  
          d.head()
### 인공신경만 모델 여러개에 대한 교차검증 함수
- models_cv(모델들(여러개의 모델), 트레이닝 데이터(X값=칼럼=피쳐=열) ,  타겟 데이터(맞춰야하는 데이터), 5번 교차 검증을 할 것이고 기본값이기에 안적어도 됨)
- -> EX :  models_cv(models, feature, label, n_splits=5)

          리턴값(아웃풋)은 판다스 데이터프레임이다 여러 모델들을 순서대로 하나씩 5번 교차검증 후 데이터 평균 결과값을 한 행마다 스택처럼 쌓아서 리턴함
          d = models_cv(models, feature, label, n_splits=5) 
          d.head()


### 4.모델 여러개 cross validation 교차검증 하기 



### 5.최종 모델 선정

In [4]:
from get import get,prepro
from factory_model import factory_model, create_models , models_cv
from cv import CV
from sklearn.metrics import accuracy_score

In [2]:
df = prepro("data/base.csv",[])
# df.to_csv("data/prepro_so_5.csv")
X_trn, y_trn, X_tst, y_tst = get('data/prepro_jung.csv')

In [3]:
model = factory_model(X_trn,y_trn,"config.json")
model.fit(X_trn,y_trn)


  0%|          | 0/20 [00:00<?, ?it/s]

Epoch 1/20, Average Training Loss: 0.7351
Epoch 2/20, Average Training Loss: 0.5957
Epoch 3/20, Average Training Loss: 0.5783
Epoch 4/20, Average Training Loss: 0.5819
Epoch 5/20, Average Training Loss: 0.5721
Epoch 6/20, Average Training Loss: 0.5670
Epoch 7/20, Average Training Loss: 0.5710
Epoch 8/20, Average Training Loss: 0.5656
Epoch 9/20, Average Training Loss: 0.5688
Epoch 10/20, Average Training Loss: 0.5663
Epoch 11/20, Average Training Loss: 0.5657
Epoch 12/20, Average Training Loss: 0.5669
Epoch 13/20, Average Training Loss: 0.5733
Epoch 14/20, Average Training Loss: 0.5655
Epoch 15/20, Average Training Loss: 0.5647
Epoch 16/20, Average Training Loss: 0.5648
Epoch 17/20, Average Training Loss: 0.5659
Epoch 18/20, Average Training Loss: 0.5646
Epoch 19/20, Average Training Loss: 0.5676
Epoch 20/20, Average Training Loss: 0.5649


In [3]:
models = create_models(X_trn, y_trn,'configW.json',2)

In [4]:
df = models_cv(models,X_trn,y_trn)
df.head()


=== DynamicANNWrapper ===


  0%|          | 0/1 [00:00<?, ?it/s]

Epoch 1/1, Average Training Loss: 0.7280

#1 Confusion Matrix: 
[[2453   54   53]
 [ 209 2416    7]
 [  56    1 2493]]

#1 교차 검증 Accuracy: 0.9509170756910359, Precision: 0.9522472939643357, Recall: 0.9512611048408726, F1: 0.9511616838138764


  0%|          | 0/1 [00:00<?, ?it/s]

Epoch 1/1, Average Training Loss: 0.7258

#2 Confusion Matrix: 
[[2494   51   30]
 [ 170 2329    6]
 [  74    1 2586]]

#2 교차 검증 Accuracy: 0.9571114843043534, Precision: 0.958438105501454, Recall: 0.9566997717950191, F1: 0.9570515198499031


  0%|          | 0/1 [00:00<?, ?it/s]

Epoch 1/1, Average Training Loss: 0.7360

#3 Confusion Matrix: 
[[2419   89   31]
 [ 173 2463   10]
 [  48    4 2504]]

#3 교차 검증 Accuracy: 0.9541402919519442, Precision: 0.9545976275385639, Recall: 0.9544106708221766, F1: 0.9542896457347972


  0%|          | 0/1 [00:00<?, ?it/s]

Epoch 1/1, Average Training Loss: 0.7298

#4 Confusion Matrix: 
[[2446   61   55]
 [ 177 2398   11]
 [  46    2 2545]]

#4 교차 검증 Accuracy: 0.9545278387805193, Precision: 0.9551903622191764, Recall: 0.9545041155689122, F1: 0.9545184317374233


  0%|          | 0/1 [00:00<?, ?it/s]

Epoch 1/1, Average Training Loss: 0.7320

#5 Confusion Matrix: 
[[2354  176  136]
 [  57 2463   13]
 [  30    0 2512]]

#5 교차 검증 Accuracy: 0.9467769022090169, Precision: 0.9472243177773704, Recall: 0.9478445988684157, F1: 0.946634968821017

## 평균 검증 Accuracy: 0.952694718587374
## 평균 검증 Precision: 0.9535395414001802
## 평균 검증 Recall: 0.9529440523790793
## 평균 검증 F1: 0.9527312499914034
## 평균 confusion_matrix: [[2433   86   61]
 [ 157 2413    9]
 [  50    1 2528]]
## 평균 early_stopping_epoch: nan

=== DynamicANNWrapper ===


c:\Users\user\miniconda3\envs\venv\lib\site-packages\numpy\core\fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
c:\Users\user\miniconda3\envs\venv\lib\site-packages\numpy\core\_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)


  0%|          | 0/1 [00:00<?, ?it/s]

Epoch 1/1, Average Training Loss: 0.7170

#1 Confusion Matrix: 
[[2452   63   45]
 [ 174 2439   19]
 [  37    0 2513]]

#1 교차 검증 Accuracy: 0.9563420304830793, Precision: 0.9569170392194492, Recall: 0.9566581428670758, F1: 0.956453568853408


  0%|          | 0/1 [00:00<?, ?it/s]

Epoch 1/1, Average Training Loss: 0.7273

#2 Confusion Matrix: 
[[2499   48   28]
 [ 190 2310    5]
 [  75    0 2586]]

#2 교차 검증 Accuracy: 0.9553029324376695, Precision: 0.9570559980388275, Recall: 0.9548187442061837, F1: 0.9552355537312268


  0%|          | 0/1 [00:00<?, ?it/s]

Epoch 1/1, Average Training Loss: 0.7205

#3 Confusion Matrix: 
[[2372  120   47]
 [ 113 2517   16]
 [  32    1 2523]]

#3 교차 검증 Accuracy: 0.9574990311329286, Precision: 0.957387235119251, Recall: 0.9575208135560006, F1: 0.9574362396687327


  0%|          | 0/1 [00:00<?, ?it/s]

Epoch 1/1, Average Training Loss: 0.7404

#4 Confusion Matrix: 
[[2479   64   19]
 [ 168 2410    8]
 [  87    3 2503]]

#4 교차 검증 Accuracy: 0.9549153856090944, Precision: 0.9563364265546976, Recall: 0.9549452751038775, F1: 0.9551149357510799


  0%|          | 0/1 [00:00<?, ?it/s]

Epoch 1/1, Average Training Loss: 0.7134

#5 Confusion Matrix: 
[[2507   95   64]
 [ 154 2368   11]
 [  28    0 2514]]

#5 교차 검증 Accuracy: 0.9545278387805193, Precision: 0.9549257613545098, Recall: 0.9547349970478667, F1: 0.9547351674001939

## 평균 검증 Accuracy: 0.9557174436886582
## 평균 검증 Precision: 0.956524492057347
## 평균 검증 Recall: 0.9557355945562008
## 평균 검증 F1: 0.9557950930809282
## 평균 confusion_matrix: [[2461   78   40]
 [ 159 2408   11]
 [  51    0 2527]]
## 평균 early_stopping_epoch: nan


c:\Users\user\miniconda3\envs\venv\lib\site-packages\numpy\core\fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
c:\Users\user\miniconda3\envs\venv\lib\site-packages\numpy\core\_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)


Model  Avg Accuracy  Avg Precision  Avg Recall    Avg F1  \
0  DynamicANNWrapper0      0.952695       0.953540    0.952944  0.952731   
1  DynamicANNWrapper0      0.955717       0.956524    0.955736  0.955795   

                               Avg Confusion Matrix  Avg Early Stopping Epoch  
0   [[2433, 86, 61], [157, 2413, 9], [50, 1, 2528]]                       NaN  
1  [[2461, 78, 40], [159, 2408, 11], [51, 0, 2527]]                       NaN

In [5]:
# 'Confusion_Matrix' 칼럼 출력
confusion_matrices = df['Avg Confusion Matrix']

# apply 함수를 사용하여 리스트의 내용을 출력
print(f"Confusion Matrix:")
for row in confusion_matrices:
    print(row)


Confusion Matrix:
[[2484   70   25]
 [ 182 2390    8]
 [  71    7 2502]]
[[2471   75   33]
 [ 201 2371    8]
 [  59    3 2517]]
